### ISSUE TITLE
wrong pk icon in the navigation tree

### ISSUE THREAD

**Issue by newpcraft** [CUBRID/cubrid-manager#15]
When it shows the table list with columns, it also shows some icon whether or not a column is a primary key. However, it doesn't work well if same columns are exists in other tables.

Reproduce

1) Create two different tables but only single column share the name across two tables, and that column has a primary key like this:

```
CREATE TABLE t1 (
    a CHARACTER(1) NOT NULL,
    b CHARACTER(1) NOT NULL,
    c CHARACTER(1),
    CONSTRAINT pk PRIMARY KEY(a, b)
);
```

```
CREATE TABLE t2 (
    c CHARACTER(1) NOT NULL,
    d CHARACTER(1),
    CONSTRAINT pk PRIMARY KEY(c)
);
```

2) After run above ddl, you will see the `c` column with a primary key icon in the `t1` table even though it doesn't have a primary constraint. It seems to be happened if same column which has a primary key in other tables.

![2016-06-20 4 24 58](https://cloud.githubusercontent.com/assets/1791415/16186248/5e784548-3704-11e6-92d1-b5072fd17610.png)

**Comment by seunghun-kim** [comment]
@newpcraft I can't reproduce like your result by default configuration. If I need additional configuration for reproduce this, please announce to me. Thank you. 😄 
![2016-06-27 13 42 50](https://cloud.githubusercontent.com/assets/16603187/16368944/47169c22-3c6f-11e6-9c8d-9a382824d879.png)

**Comment by newpcraft** [comment]
@seunghun-kim I've tested it under 9.2.3.0005 version of cubrid server. And the client version is 9.3.6.004.

![2016-07-05 12 17 39](https://cloud.githubusercontent.com/assets/1791415/16573050/7f37a178-42aa-11e6-8bfb-00f608428a8d.png)

Would you please test it on above env?

**Comment by seunghun-kim** [comment]
@newpcraft I could reproduce this issue using 9.2.0 to 9.2.6 versions of CUBRID server. 
Additionally above version of 9.2.9 was not reproduced it.
I will trace this issue next week. Thank you. 😃 
![2016-07-05 16 17 20](https://cloud.githubusercontent.com/assets/16603187/16577580/033f216e-42d1-11e6-93de-dfbef1cc3b5d.png)
![2016-07-05 16 21 56](https://cloud.githubusercontent.com/assets/16603187/16577582/0916ebe4-42d1-11e6-8f9e-32cb54e9bdf5.png)

**Comment by seunghun-kim** [comment]
@newpcraft 
I have found why non pk column shows as pk column.
That is JDBC driver's bug in 9.2.0 to 9.2.6.
When users expanding the `TreeViewer` in hosts navigator, below codes work for find the pk colums.

- `GetUserClassColumnsTask#getColumns()`
```java
	DatabaseMetaData dbmd = connection.getMetaData();
	columns = SchemaUtil.getTableColumn(databaseInfo, connection, tableName);

	rs = dbmd.getPrimaryKeys(null, null, tableName);
	List<String> pkColumns = new ArrayList<String>();
	while (rs.next()) {
		pkColumns.add(rs.getString("column_name"));
	}
	QueryUtil.freeQuery(rs);
```

But `CUBRIDDatabaseMetaData#getPrimaryKeys()` is not work as expected in 9.2.0 to 9.2.6.
I will PR after fix it.

**Comment by seunghun-kim** [comment]
I have additional tested about this.

According to my test result, this is not JDBC Driver bug but engine's bug.
I made test program `test.jar` that contains JDBC driver for 9.2.6 and 10.0.0.
If you want to execute this program, you should write the database connection properties in `conf.properties`.

Below image is running result of test program.
Argument 9 is choosing the 9.2.6 JDBC Driver and 10 is 10.0.0.
![test1](https://cloud.githubusercontent.com/assets/16603187/21705312/8cf62c46-d402-11e6-8bcc-5f937e833f62.png)

Below image is ran at same database in version 10.0.0.
![test2](https://cloud.githubusercontent.com/assets/16603187/21705315/90263852-d402-11e6-9fc5-b4e2ad51bf5a.png)

Below image is ran at same database in version 9.2.6.
![test3](https://cloud.githubusercontent.com/assets/16603187/21705317/92d96f6a-d402-11e6-8095-5ff3ea6fe262.png)

I attach test program: [test.tar.gz](https://github.com/CUBRID/cubrid-manager/files/688879/test.tar.gz)

**Comment by seunghun-kim** [comment]
This issue was fixed.
Please reference #49.
