### ISSUE TITLE
unable to locate its companion shared library error on mac os sierra

### ISSUE THREAD

**Issue by newpcraft** [CUBRID/cubrid-manager#19]
![not_found_companion_library](https://cloud.githubusercontent.com/assets/1791415/20515452/1b03a6d6-b0d5-11e6-9507-2686a5ff755c.png)

Since mac os sierra, it couldn't be run CUBRID Manager due to cubridmanager.ini uses a relative path with required libraries.

**Comment by newpcraft** [comment]
Workaround:

In order to run CUBRID Manager on latest version of mac os before patch release, you can change cubridmanager.ini file as the following steps:

1) open CUBRID Manager app by using `Show Package Contents`

![1](https://cloud.githubusercontent.com/assets/1791415/20515680/036cac42-b0d6-11e6-88cf-20764375e6d7.png)

2) and then you can find cubridmanager.ini on the following path

![2](https://cloud.githubusercontent.com/assets/1791415/20515686/0e1cc820-b0d6-11e6-9d12-985e9ab25fb3.png)

3) edit the file and you can see like this

```
-startup
../../../plugins/org.eclipse.equinox.launcher_1.1.0.v20100507.jar
--launcher.library
../../../plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.0.v20100503
```

4) make it change by an absolute path rather than relative:

```
-startup
/Users/user1/CUBRIDManager/plugins/org.eclipse.equinox.launcher_1.1.0.v20100507.jar
--launcher.library
/Users/user1/CUBRIDManager/plugins/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.1.0.v20100503
```

5) when you finish such steps, you can run just clicking twice CUBRID Manager app as before.

**Comment by seunghun-kim** [comment]
@newpcraft I also experienced same issue like you. I also experienced same issue like you. I will research the solution about it. Thanks 😄

**Comment by newpcraft** [comment]
@seunghun-kim 

In order to resolve the problem, we may need to upgrade to the latest version of eclipse platform, however, it takes time to do that. Even though we upgrade the version of platform, it would not be complete

Except changing the version of eclipse platform, there are another way to provide an installer using bash script that makes an user run it first. And then, it makes symbolic links in CUBRIDManager.app/Contents/MacOS/ from `configuration`, `driver`, `dropins`, `features`, `p2`, `plugins` in CUBRIDManager installed path. Even if os will copy CUBRIDManager.app to the temporary folder, but, due to symbolic links it may work as same as before(but I didn't test it).

Here is a script what I scratched to test, just for your reference:

```
#!/bin/bash
CMAPP_HOME=`dirname "$0"`
cd $CMAPP_HOME/cubridmanager.app/Contents/MacOS
ln -sf $CMAPP_HOME/configuration
ln -sf $CMAPP_HOME/driver
ln -sf $CMAPP_HOME/dropins
ln -sf $CMAPP_HOME/features
ln -sf $CMAPP_HOME/plugins
ln -sf $CMAPP_HOME/p2
```

Would you test such scenario whether or not it runs such way as well as it upgrades through the auto update feature also using above way?

**Comment by seunghun-kim** [comment]
@newpcraft 

I was test the CM in sierra with your script and found one problem.
Generated symbolic link is pointing wrong target like below image.
![2016-12-02 5 11 48](https://cloud.githubusercontent.com/assets/16603187/20827183/9347df78-b8b3-11e6-8b1d-7ad9ca97ebd2.png)


So, I have modified your script as below and test it successfully.
```
#!/bin/bash
CMAPP_HOME=`pwd`
cd $CMAPP_HOME/cubridmanager.app/Contents/MacOS
ln -sf $CMAPP_HOME/configuration
ln -sf $CMAPP_HOME/driver
ln -sf $CMAPP_HOME/dropins
ln -sf $CMAPP_HOME/features
ln -sf $CMAPP_HOME/plugins
ln -sf $CMAPP_HOME/p2
sed "s/.\/..\/..//g" cubridmanager.ini > tmp
mv tmp cubridmanager.ini
```
How about above script? I need your feedback.

I couldn't test in auto update feature but I will that test as soon as possible. 

Thank you.
